os:
  - linux
  - osx
language: cpp
compiler:
  - clang
  - gcc
install: []
script:
  - scripts/travis.sh
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
